Dev2
Qolit3/react-burger pull request #1
Opened 2022-08-18 22:52 UTC by Qolit3

2022-08-19 08:34 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная


* Верстка хорошая
* Отлично, что используете пустой массив зависимостей `[]`, чтобы `useEffect` сработал 1 раз

 но есть некоторые недочеты: 


* Файл `App.test.js` нужно удалить, так как он не относится к проекту
* Нужно удалить лишние файлы http://joxi.ru/EA4YWBvSXkLnVr 
* `app.css` нужно  сделать модулем `app.module.css`, а в компоненте использовать модульные классы, а не строки 
* все `css`-файлы нужно сделать модулем `.module.css` по заданию, а в компоненте использовать модульные классы, а не строки 
* Скрин http://joxi.ru/p27YKB7SLbMjvr . По заданию должен появляться скролл, если список ингредиентов не вмещается в высоту экрана. Страница не должна скроллиться сама вся. Только ингредиенты
* Любой ответ от сервера нужно проверять на `ok` и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.
* `throw new Error` не стоит использовать в `catch`, ведь этот блок создан как раз для отлова ошибок, а не выкидывания их опять наружу
* `(props: any)` тип `any` нельзя использовать для пропсов. Их нужно правильно типизировать. Если не хотите типизировать пока с помощью `typescirpt`, то нужно убрать расширение `ts` у файлов и типизировать пропсы с помощью `propTypes`
* для контента модального окна заказа  по заданию должен быть компонент `OrderDetails`
* Для атрибута `key` лучше всего использовать уникальный `id` : у карточки как раз есть такой только с нижним подчеркиванием `_id`
* тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно
* `ReactDOM.createPortal` нужно только в `Modal` указать. Вся верстка будет уходить одним порталом оттуда

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте **работоспособность проекта** и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

Удачного рефакторинга кода.

2022-08-19 08:34 UTC, gennady-bars commented on src/components/app/app.tsx
> +    .then(res => res.json())
`    .then(res => res.json())
`

Любой ответ от сервера нужно проверять на `ok` и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.


```js
.then(res => {
                if (res.ok) {
                    return res.json();
                }
                return Promise.reject(`Ошибка ${res.status}`);
            })

```

2022-08-19 08:34 UTC, gennady-bars commented on src/components/app/app.tsx
> +      .catch(res => {throw new Error(res)});
`throw new Error` не стоит использовать в `catch`, ведь этот блок создан как раз для отлова ошибок, а не выкидывания их опять наружу


Тут пока можно `console.log` указать

2022-08-19 08:34 UTC, gennady-bars commented on src/components/app/app.tsx
> +  }, [])
Отлично, что используете пустой массив зависимостей `[]`, чтобы `useEffect` сработал 1 раз

2022-08-19 08:34 UTC, gennady-bars commented on src/components/burger-constructor/burger-constructor.tsx
> +const BurgerConstructor = (props: any) => {
`(props: any)` тип `any` нельзя использовать для пропсов. Их нужно правильно типизировать. Если не хотите типизировать пока с помощью `typescirpt`, то нужно убрать расширение `ts` у файлов и типизировать пропсы с помощью `propTypes`

2022-08-19 08:34 UTC, gennady-bars commented on src/components/burger-constructor/burger-constructor.tsx
> +        <div className="mr-25 ml-25">
для контента модального окна заказа  по заданию должен быть компонент `OrderDetails`


```jsx

      <Modal handleClose={closeModal} active={active}>
        <OrderDetails orderNumber={'123456'} />
      </Modal>


```

2022-08-19 08:34 UTC, gennady-bars commented on src/components/ingredients-block/ingredients-block.tsx
> +    return props.block.ingredients.map((item: any, index: any) => <Ingredient key={index} item={item}/>)
` key={index} `

Для атрибута `key` лучше всего использовать уникальный `id` : у карточки как раз есть такой только с нижним подчеркиванием `_id`
[Почему индекс не нужно использовать, можно прочитать тут:]( https://medium.com/russian/%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BA%D0%BB%D1%8E%D1%87%D0%B0-%D0%B0%D0%BD%D1%82%D0%B8-%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-56bab8ada309)

2022-08-19 08:34 UTC, gennady-bars commented on src/components/ingredients-block/ingredients-block.tsx
> +          _id: PropTypes.string,
тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2022-08-19 08:34 UTC, gennady-bars commented on src/components/burger-ingredients/burger-ingredients.tsx
> +          _id: PropTypes.string,
тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2022-08-19 08:34 UTC, gennady-bars commented on src/components/ingredient/ingredient.tsx
> +    _id: PropTypes.string,
тип для ингредиента (propTypes) повторяется в некоторых компонентах. Не нужно его копировать. Это очень сложный объект. Нужно вынести его в константу `ingredientType` в отдельный файл `types.js` в папку `utils` и импортировать туда, где нужно

2022-08-19 08:34 UTC, gennady-bars commented on src/components/modal/modal.tsx
> +          document.removeEventListener('keydown', handleKeydown)
правильно удаляется обработчик

2022-08-19 08:34 UTC, gennady-bars commented on src/components/modal/modal.tsx
> +  function handleKeydown(e:any) {
тип `KeyboardEvent` для событий клавиатуры можно тут использовать 

```js

  function handleKeydown(e: KeyboardEvent) {


```

2022-08-19 08:34 UTC, gennady-bars commented on src/components/modal-overlay/modal-overlay.tsx
> +  return ReactDOM.createPortal(
`ReactDOM.createPortal` нужно только в `Modal` указать. Вся верстка будет уходить одним порталом оттуда

2022-08-20 08:09 UTC, gennady-bars reviewed
Еще немного и все будет отлично:

* Скрин http://joxi.ru/MAj5QOltdDjG52 . В консоли ошибки `key`

2022-08-20 08:09 UTC, gennady-bars commented on src/components/burger-constructor/burger-constructor.jsx
> +        <div key={item._idx} className={`${styles.ingredient} mt-4`}>
`_idx` не существует в `item`. Есть `_id`


```js

key={item._id}

```

2022-08-22 13:55 UTC, gennady-bars reviewed
Кое-что нужно подправить:

* в консоли ошибка `key` все еще.  Думаю, это из-за сортировки ингредиентов при кликах на табы. Вам нужно ее пока удалить и отображать просто список ингредиентов, как он есть

**Можно лучше**

* При кликах на табы `Булки, Соусы, Начинки` можно сделать логику **`плавного`** скролла до секции. Это можно сделать с помощью хука `useRef` и методом ` scrollIntoView`. Нужно установить для 3х секций 3 `useRef` и следить за изменением табов при кликах на них через функцию клика. Как меняется таб, то запускается ` scrollIntoView ` со значением ` behavior: "smooth"`
Подробнее про `useRef` тут https://ru.reactjs.org/docs/hooks-reference.html#useref
Подробнее про ` scrollIntoView` тут https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-08-23 07:35 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-10-06 16:54 UTC, vadmas reviewed
Хорошая работа.
Приложение приобретает готовый вид, видно как студент прогрессирует по мере прохождения курса.
В положительную сторону хочется отметить:
- Используемые стили портированы как модули
- Работа с redux реализована хорошо (есть небольшие замечания ниже)
- Для компонентов с пропсами описан propTypes
- Корректно выполняются запросы к API. Для каждого экшена, который связан с запросом к Api создан усилитель - отлично!
- Взаимодействие компонентов с redux сторами реализована через хуки - очень хорошо!
- В целом функционал работы приложения выполнен хорошо, практически все экшены отрабатывают должным образом
  (есть небольшое замечание по удалению ниже)

**Но есть несколько замечаний:**

**Замечания которые необходимо будет исправить:**
- Необходимо уcтановить пакет prop-types в package.json. Типы пропсов описаны - отлично! Однако сам пакет не установлен
- Разбить редъюсер (otherReducers) и экшены (otherActions) на редъюсеры и экшены отвечающие за конкретную сущность
  (смотри коммент в otherReducers.jsx)
- В компоненте BurgerConstructor, методы renderIngredients и renderConstructrList (поправить название на renderConstructorList)
  - вынести в дочерние компоненты.
  Так же метод renderIngerdientsBlocks в компоненте BurgerIngredients.
- При попытке удаления ингредиента из конструктора бургера, приложение падает - поправить
- При оформлении заказа, в запросе order отправляем айдишники ингредиентов - верно.
  Однако айдишник булки должен быть и первым и последним (на данный момент в конце массива не ставится айдшиник булки)


Так же стоит учесть комментарии, оставленные в коде.

**Места, в которых можно улучшить проект:**
- В пакетах package.json есть @reduxjs/toolkit, однако сторы redux (экшены и редьюсеры)
  описаны в классическом стиле, без использования слайсов (преимуществ данной библиотеки).
  О работе с данной библиотекой и быстром внедрении в проект,
  можно почитать здесь: https://redux-toolkit.js.org/tutorials/quick-start
- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект.
  Это хорошие рекомендации, которых следовало бы придерживаться.
- Расчет общей стоимости бургера лучше реализовать с использованием хука useMemo (смотри коммент в BurgerConstructor).
  Тоже самое касается и расчета параметров buns, sauces, mains - (смотри коммент в BurgerIngredients)
- Можно так же реализовать скролл к определенному разделу ингредиентов при клике на соответствующим таб раздела.

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +  const [active, setActive] = React.useState(false);
Лучше придерживаться принципа единообразия импортов и описания хуков.
К примеру useEffect импортируется путем деструктуризации объекта React
useState уместно импортировать подобным образом

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +  let totalPrice = 0;
Данный параметр целесообразнее расчитывать с уиспользованием хука useMemo
Подробнее о данном хуке можно узнать здесь: https://ru.reactjs.org/docs/hooks-reference.html#usememo

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +  let renderList = [];
Соответственно данная переменная уйдет, если renderIngredients и renderConstructrList
вынести в компоненты (смотри коммент ниже)

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +  const renderIngredients = () => {
Лучше выделить отдельные компоненты которые реализовывали бы данную логику рендеринга

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +    if(list.length){
Данное условие проще описать как
if(!list.length) return <p...
return renderIngredients

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-constructor/burger-constructor.jsx
> +        if(item.type === 'bun') {
Строковое значение bun - часто используется в коде. Уместнее было бы вынести ее в константы.

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const ingredientsSauces = [sauces, mains, buns];
Перед pull-реквестом лучше избавляться от неиспользуемых переменных (ingredientsSauces, ingredientsMains)

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  useEffect(() => {
Сильно упростит код, и поможет избавиться от данного useEffect, если buns, sauces и mains - будут рассчитываться из хука useMemo

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const renderIngerdientsBlocks = () => {
Уместнее вынести в данную утилиту в какой нибудь дочерний компонент

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      setCurrent('0')
Строковые значения 0, 1, 2 -  так же лучше вынести в константы и константы и обозначить условным наименованием

2022-10-06 16:54 UTC, vadmas commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    console.log(current)
Так же перед pull-реквестом лучше избавляться от console.log, debugger

2022-10-06 16:54 UTC, vadmas commented on src/components/ingredient/ingredient.jsx
> +import PropTypes from 'prop-types';
Неиспользуемый импорт

2022-10-06 16:54 UTC, vadmas commented on src/components/ingredients-block/ingredients-block.jsx
> +    type = 'BUNS'
BUNS, SAUCES, MAINS - уместнее вынести в константы

2022-10-06 16:54 UTC, vadmas commented on src/services/reducers/otherReducers.jsx
> +export const otherReducers = (state = initialstate, action) => {
Уместнее разделить данный редьюсер на редьюсер конструктора бургера и редьюсер по работе с модальными окнами
Лучше стараться по максимуму декомпозировать логику сторов по сущностям

2022-10-06 16:54 UTC, vadmas commented on src/util/types.js
> +const ingredientType = PropTypes.shape({
Подробно описаны типы свойств объектов - так держать!

2022-10-11 13:36 UTC, vadmas commented
Прикрепил видео воспроизведения баги при удалении ингредиента
https://user-images.githubusercontent.com/113043395/195105794-10591681-357c-4ba7-af05-8552e02537f8.mp4

2022-10-14 17:41 UTC, vadmas commented
Отлично, все критичные комментарии исправлены.  Работу принимаю. Удачи в дальнейшем обучении!

2022-11-18 14:36 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации:

* Не могу создать заказ. Ошибка в консоли https://disk.yandex.ru/i/HomjM_dK4KKl-w 
* Не выполнена часть задания:
* нет автологина
* по заданию нужно сделать логику, при которой бы показывался попап с деталями ингредиента, если кликнуть по ингредиенту, но если скопировать ссылку на ингредиент при открытом попапе и **вставить в окно браузера**, то должна уже показываться **страница** с этими деталями. 
* если **перезагрузить** страницу с открытым попапом ингредиента, то этот открытый попап опять должен появляться (или страница с деталями). А сейчас ничего не отображается после перезагрузки

Еще заметил ошибки:

* Не стоит выбирать булку за пользователя при загрузке сайта. Нужно оставить в этом месте текст: `Пожалуйста, перенесите сюда булку и ингредиенты для создания заказа` или что-то в этом роде.
* Неправильно работает перетаскивание ингредиента снизу вверх внутри заказа. Скрин https://disk.yandex.ru/i/P0nAgoAW0ktn0w . Не могу с самого низа перетащить в самый верх и обратно

2022-11-21 13:59 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

К сожалению, работу придется отклонить без потери итерации:

* не могу восстановить пароль. Не идет переход на `reset-password` после отправки на мэйл кода.
* не могу создать заказ. Скрин  https://disk.yandex.ru/i/NLJX5qsbq5K5Eg 
* нет автологина
* пользователь не должен **напрямую** попасть на маршрут `/reset-password`. На эту страницу **никакой** пользователь не должен попадать напрямую. Только после нажатия на `восстановить пароль` нужно делать переход на эту страницу. Для этого нужно сделать проверку, был ли пользователь на странице `forgot-password` перед тем, как попасть на `reset-password`
* Нужно картинку тоже центрировать на странице с ингредиентов. Скрин https://disk.yandex.ru/i/UDUo-MLMQm9JAQ 
* По заданию нужно сделать логику **переключения табов**, когда идет **скролл** ингредиентов в списке слева. Это сделать можно с помощью библиотеки `react-intersection-observer`
* Если пользователь **не авторизован** и пытается попасть на защищённый маршрут — его **переадресовывает** на маршрут `/login`. После авторизации пользователь автоматически переадресовывается на тот маршрут, к которому у него **не получилось** получить доступ ранее. Это делается с помощью ` return <Redirect to={location?.state?.from || '/'} />;` (эти данные записываются в `ProtectedRoute`, а используются в `Login` для `Redirect`)
 



**Можно лучше**

*  при клике на **логотип** обычно идет переход на главную страницу

2022-12-01 16:23 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная, но есть некоторые недочеты: 


* Любой ответ от сервера нужно проверять на `ok` (на **корректность**) и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.
* У Вас повторяется код **проверки ответа** во всех запросах. Чтобы этого избежать, нужно сделать отдельную функцию `checkResponse`, которая будет проверять ответ от сервера
* Когда я собрал заказ и нажал на кнопку, меня перекинуло на логин, а после логина я вернулся обратно к заказу, а его нет. Он не должен очищаться, пока его не отправили на сервер
* Так и не могу отправить заказ на сервер. Ошибка https://disk.yandex.ru/i/3508GGJ1lMFkdQ . Токен плохой (так в ответе от сервера пишут). Но после пару перезагрузок страницы все заработало. Нужно всегда свежий токен получать из `cookie` при действиях, иначе будут такие баги
*  **Обработчик сабмита** нужно навешивать только на тег `form` с событием `submit`, а не на кнопку сабмита с событием `click`, так как сабмит формы происходит ещё при нажатии `Enter`, и он не будет работать, если навесить обработчик клика на кнопку только. **Это нужно исправить везде, где есть инпуты и форма**
* `key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого).
* Нужно генерировать uuid при создании экшена (желательно, в **`action creator`**). И созданный uuid должен приходить в экшене в `payload` или как отдельное поле, или сразу как часть объекта ингредиента. Посоветуйтесь с наставником, пожалуйста.
* Вам нужно использовать средства **роутинга** для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://reactrouter.com/web/example/modal-gallery . Пожалуйста, посоветуйтесь с наставником.






**Можно лучше**


*  при клике на **логотип** обычно идет переход на главную страницу
*  желательно **очищать конструктор** после успешного получения номера заказа с сервера в блоке `then`, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты


Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте **работоспособность проекта** и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

Удачного рефакторинга кода.

2022-12-01 16:23 UTC, gennady-bars commented on src/components/profile-change/profile-change.jsx
> +    .then(res => res.json())
`    .then(res => res.json())
`

Любой ответ от сервера нужно проверять на `ok` (на **корректность**) и вызывать ошибку, если ответ не `ok`. Таким образом, в `catch` Вы будете ловить и ошибки сервера, и ошибки невалидных данных.


```js
.then(res => {
                if (res.ok) {
                    return res.json();
                }
                return Promise.reject(`Ошибка ${res.status}`);
            })

```

------------------------


```js
.then(res => {
                if (res.ok) {
                    return res.json();
                }
                return Promise.reject(`Ошибка ${res.status}`);
            })

```

У Вас повторяется код **проверки ответа** во всех запросах. Чтобы этого избежать, нужно сделать отдельную функцию `checkResponse`, которая будет проверять ответ от сервера:

```js
function checkResponse(res) {
        // тут проверка ответа
    }

```

Ее нужно поместить в папку `utils` и импортировать туда, где нужна проверка на `ok`.

и теперь можно удалить кучу ненужно повторного кода и заменить его этим:

```js
 .then(checkResponse)

```

Обратите внимание, что передается только **ссылка** на функцию. Не нужно ее вызывать. Она сама вызовется, так как в `then` нужно передавать именно **функцию**, а не **вызов** функции.

-----------------------------------------

**Можно лучше**

Можно сделать **универсальную функцию запроса с проверкой ответа**, чтобы не дублировать эту проверку в каждом запросе:

```js

  function request(url, options) {
    // принимает два аргумента: урл и объект опций, как и `fetch`
    return fetch(url, options).then(checkResponse)
  }

```

И теперь просто нужно заменить все `fetch` на `request`. Все остальное будет без изменений. Код станет чище

2022-12-01 16:23 UTC, gennady-bars commented on src/services/actions/allIngredientsAction.jsx
> +          type: GET_ALL_INGREDIENTS_FAILED
`        type: GET_ALL_INGREDIENTS_FAILED
`

**Можно лучше**

Чтобы **не дублировать** типы экшенов и сами объекты с `type`, принято выносить их в отдельные функции, называемые **`action creator`** (функция, которая возвращает объект с `type`). Это позволяет сделать **понятное название** для функции, которое будет говорить, что делает она, и избавит от повтора объекта с `type` в коде. Подробнее тут: [https://rajdee.gitbooks.io/redux-in-russian/content/docs/basics/Actions.html#генераторы-экшенов-action-creators](https://rajdee.gitbooks.io/redux-in-russian/content/docs/basics/Actions.html#%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D1%8D%D0%BA%D1%88%D0%B5%D0%BD%D0%BE%D0%B2-action-creators)

2022-12-01 16:23 UTC, gennady-bars commented on src/services/actions/createOrderAction.jsx
> +        'authorization': `Bearer ${accessToken}`,
`        'authorization': `Bearer ${accessToken}`,
`

* Так и не могу отправить заказ на сервер. Ошибка https://disk.yandex.ru/i/3508GGJ1lMFkdQ . Токен плохой (так в ответе от сервера пишут). Но после пару перезагрузок страницы все заработало. Нужно всегда свежий токен получать из `cookie` при действиях, иначе будут такие баги


```js
        'authorization': `Bearer ${getCookie('accessToken')}`,



```

2022-12-01 16:23 UTC, gennady-bars commented on src/pages/login/Login.jsx
> +  const [pass, setPass] = useState('');
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = (event) => {
    const {value, name} = event.target;
    setValues({...values, [name]: value});
  };
  return {values, handleChange, setValues};
}

```

Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```jsx
  const {values, handleChange, setValues} = useForm({});

```

2022-12-01 16:23 UTC, gennady-bars commented on src/pages/login/Login.jsx
> +          <Button type='primary' size='small' onClick={onLoginClick} htmlType='submit'>Войти</Button>
`onClick={onLoginClick}`

это нужно удалить с кнопки


**Обработчик сабмита** нужно навешивать только на тег `form` с событием `submit`, а не на кнопку сабмита с событием `click`, так как сабмит формы происходит ещё при нажатии `Enter`, и он не будет работать, если навесить обработчик клика на кнопку только. **Это нужно исправить везде, где есть инпуты и форма**

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +        <ConstructorItem key={uuidv4()} ingredient={list.find(item => item.order === i)}/>
`key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого).

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +      <ConstructorItem key={uuidv4()} ingredient={bun} position={'bottom'}/>
`key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого).

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +      <ConstructorItem key={uuidv4()} ingredient={bun} position={'top'}/>
`key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого).

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +        <ConstructorItem key={uuidv4()} ingredient={list.find(item => item.order === i)}/>
в `key` нужно указывать только **1 раз созданный** уникальный `uuid` ингредиента, иначе Вы сейчас меняете его при каждой перерисовке, что приводит к тому, что Реакт не может уследить за перемещением компонентов, и это может сломать логику `DnD`

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +        <ConstructorItem key={uuidv4()} ingredient={list.find(item => item.order === i)}/>
Нужно генерировать uuid при создании экшена (желательно, в **`action creator`**). И созданный uuid должен приходить в экшене в `payload` или как отдельное поле, или сразу как часть объекта ингредиента. Посоветуйтесь с наставником, пожалуйста.

2022-12-01 16:23 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +        <ConstructorItem key={uuidv4()} ingredient={list.find(item => item.order === i)}/>
А в `key` будет уже просто **key={ item.uuid }**

2022-12-01 16:23 UTC, gennady-bars commented on src/components/app/app.jsx
> +    window.history.back();
`    window.history.back();
`

не стоит в реакте использовать  ` window.history`


В реакте используют хук `useHistory`. Его методы не перезагружают страницы

2022-12-01 16:23 UTC, gennady-bars commented on src/components/app/app.jsx
> +        <Routes>
Вам нужно использовать средства **роутинга** для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://reactrouter.com/web/example/modal-gallery . Пожалуйста, посоветуйтесь с наставником.

2022-12-01 16:23 UTC, gennady-bars commented on src/components/app/app.jsx
> +        <Routes>
` background` в 6й версии роутинга можно определять и передавать в ` Routes` вот так:
 
```jsx
  const background = location.state?.background

  return (
      <Routes location={background ?? location}>

```

2022-12-02 12:36 UTC, Qolit3 commented on src/components/profile-change/profile-change.jsx
> +    .then(res => res.json())
К можно лучше: Но для этого же всё равно надо будет объявлять и наполнять объект `options`. Разве станет он сильно чище?

2022-12-09 11:51 UTC, gennady-bars commented on src/components/profile-change/profile-change.jsx
> +    .then(res => res.json())
Вам не нужно будет повторять `.then(checkResponse)` везде в запросах. В этом чистота

2022-12-09 11:55 UTC, gennady-bars commented on src/components/profile-change/profile-change.jsx
> +    .then(checkResponse)
` .then(checkResponse)` дублируется везде

**Можно лучше**

Можно сделать **универсальную функцию запроса с проверкой ответа**, чтобы не дублировать эту проверку в каждом запросе:

```js

  function request(url, options) {
    // принимает два аргумента: урл и объект опций, как и `fetch`
    return fetch(url, options).then(checkResponse)
  }

```

И теперь просто нужно заменить все `fetch` на `request`. Все остальное будет без изменений. Код станет чище

2022-12-09 11:55 UTC, gennady-bars commented on src/util/actionCreators.jsx
> +
* `actionCreators.jsx` относятся к редаксу, поэтому нужно поместить внутрь `services`

2022-12-09 11:55 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +        <ConstructorItem key={uuidv4()} ingredient={list.find(item => item.order === i)}/>
Это не исправили https://github.com/Qolit3/react-burger/pull/1#discussion_r1037316522

2022-12-09 11:56 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +      <ConstructorItem key={uuidv4()} ingredient={bun} position={'top'}/>
* `key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого). Скрин https://disk.yandex.ru/i/zFgBvtFeW6U0tQ

2022-12-09 11:56 UTC, gennady-bars commented on src/components/render-ingredients/render-ingredients.jsx
> +      <ConstructorItem key={uuidv4()} ingredient={bun} position={'bottom'}/>
* `key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого). Скрин https://disk.yandex.ru/i/zFgBvtFeW6U0tQ

2022-12-09 12:01 UTC, gennady-bars reviewed
Еще немного и все будет отлично:

* `actionCreators.jsx` относятся к редаксу, поэтому нужно поместить внутрь `services`
* Это не исправили https://github.com/Qolit3/react-burger/pull/1#discussion_r1037316522
* `key={uuidv4()}` нельзя динамически создавать что-то в `key`. Для атрибута `key` нужно использовать только что-то постоянное, что всегда есть при элементе, иначе реакт не поймет, что этот компонент уже был отрисован и ничего в нем не изменилось (реакт начнет подгружать данные, картинки и тд из-за этого). Скрин https://disk.yandex.ru/i/zFgBvtFeW6U0tQ 
* Когда я собрал заказ и нажал на кнопку, меня перекинуло на логин, а после логина я вернулся обратно к заказу, а его нет. Он не должен очищаться, пока его не отправили на сервер

2022-12-09 12:01 UTC, gennady-bars commented on src/util/actionCreators.jsx
> +import { GET_ALL_INGREDIENTS_FAILED } from "../services/actions/allIngredientsAction";
* Когда я собрал заказ и нажал на кнопку, меня перекинуло на логин, а после логина я вернулся обратно к заказу, а его нет. Он не должен очищаться, пока его не отправили на сервер

2022-12-11 17:23 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)


К сожалению, работу придется отклонить без потери итерации


* не исправлено замечание про `key`. Скрин https://disk.yandex.ru/i/AvktwLTPDdI0tQ  . Ссылка на прошлое замечание https://github.com/Qolit3/react-burger/pull/1#pullrequestreview-1211560190

2022-12-12 10:23 UTC, gennady-bars reviewed
Уже почти все отлично, но:

* при добавлении булки в заказ в консоли ошибка `key`. Скрин https://disk.yandex.ru/i/LR3EUAlS7RYMkw 
* ` key` нужно удалить из пропсов. Все работает уже с `key={item.key}`  в  `RenderIngerdients`

--------------


и не забудьте смерждить ветки после принятия работы. А то все ревью в одном пулл-реквесте проходят.  А должны быть под разные спринты разные ветки быть

2022-12-12 10:23 UTC, gennady-bars commented on src/components/constructor-item/constructor-item.jsx
> +export const ConstructorItem = ({ingredient, position, key}) => {
* при добавлении булки в заказ в консоли ошибка `key`. Скрин https://disk.yandex.ru/i/LR3EUAlS7RYMkw 



` key` нужно удалить из пропсов. Все работает уже с `key={item.key}`  в  `RenderIngerdients`

2022-12-12 10:23 UTC, gennady-bars commented on src/components/constructor-item/constructor-item.jsx
> +        <div  key={key}  className={`${styles.ingredient}`}>
Атрибут `key` нужен только при отрисовке **массивов** компонентов. Просто так внутри компонентов не нужно его указывать.

2022-12-12 10:23 UTC, gennady-bars commented on src/components/constructor-item/constructor-item.jsx
> +        <div  key={key}  className={`${styles.ingredient} mt-4`}>
Атрибут `key` нужен только при отрисовке **массивов** компонентов. Просто так внутри компонентов не нужно его указывать.

2022-12-12 10:23 UTC, gennady-bars commented on src/components/constructor-item/constructor-item.jsx
> +      <div ref={dropTarget}  key={key} >
Атрибут `key` нужен только при отрисовке **массивов** компонентов. Просто так внутри компонентов не нужно его указывать.

2022-12-13 11:39 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.


* Скрин https://disk.yandex.ru/i/-UOp4ef1RVUPmg в задании написано, как называется ветка под каждый спринт. Нужно будет так дальше делать. а не в одном `dev` все указывать

2022-12-21 06:36 UTC, andryxxa93 requested changes
Основной функционал реализован верно. Понравилось, что в проекте в правильные моменты открывается и закрывается сокет-соединение. Есть несколько замечаний, которые необходимо исправить чтобы работа была принята.

1. "Лента заказов" и "История заказов" это разные сущности. "Лента заказов" должна отображать все заказы, которые были сделаны пользователями, эта страница общедоступная, для доступа к ней не нужно логиниться. "История заказов" это история заказов залогиненного пользователя - вот её вы сейчас и реализовали. 
2. Если попытаться открыть конкретный заказ по прямой ссылке, то сначала предлагает залогиниться, а после идёт вечная загрузка этого заказа, хотя все запросы уже прошли.
<img width="1440" alt="Снимок экрана 2022-12-21 в 09 14 54" src="https://user-images.githubusercontent.com/60173362/208835050-7d5c50d3-b302-47bf-9572-397a8be0eed6.png">
3. Не работает логаут, после него пользоватeль всё равно может попадать на страницу профиля.

https://user-images.githubusercontent.com/60173362/208835485-90f1fa12-6f14-4743-99e4-4dd74a62a34c.mov

4. Необходимо для каждого задания создавать отдельный pull-request а не делать все в одном и том же. Для вы можете сделать реверт последнего коммита и смержить ветку в main. Потом создать новую ветку как написано в задании `month-9/step-2` и в неё черипикнуть ранее ревертнутый коммит. На основе этой ветки и создайте pull-request. 

Удачных правок!

2022-12-21 06:36 UTC, andryxxa93 commented on data.json
> +[
**Можно лучше**
Этот файл необходимо удалить

2022-12-21 06:36 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    }
**Можно лучше**
Рекомендую написать код иначе, чтобы избежать лишнего вызова `getCookie`
Например так:
```
const refreshToken = getCookie('refreshToken');
if(refreshToken) {
      dispatch(loginUpdate(refreshToken))
    }
```

2022-12-21 06:36 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  /*if(allIngredients.length) {
**Можно улучшить**
Ненужный код лучше удалять

2022-12-23 07:44 UTC, merged